Add the option to configure a PodDisruptionBudget
gardener/service-account-issuer-discovery pull request #40
Opened 2024-10-24 11:19 UTC by nweisenauer-sap

**What this PR does / why we need it**:
Adds the option to configure a PodDisruptionBudget via the values.yaml to make the sa-issuer-discovery deployment more resilient.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Added the option to configure a PodDisruptionBudget via the values.
```

2024-10-24 11:26 UTC, vpnachev requested changes

2024-10-24 11:26 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +{{- if .Values.resilience.pdb.enabled }}
In gardener organization we are using the desired replicas as a switch to enable or not the pod disruption budget. See this [example](https://github.com/gardener/gardener/blob/master/charts/gardener/gardenlet/templates/poddisruptionbudget.yaml), please apply the same approach.

2024-10-24 11:45 UTC, nweisenauer-sap commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +{{- if .Values.resilience.pdb.enabled }}
Thanks, I also added the option to configure the `unhealthyPodEvictionPolicy`, enabled by default with `AlwaysAllow`.

2024-10-24 12:16 UTC, vpnachev requested changes

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +  name: {{ include "name" . | quote }}
```suggestion
  name: {{ include "name" . }}
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +  namespace: {{ .Release.Namespace | quote }}
```suggestion
  namespace: {{ .Release.Namespace }}
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +spec:
```suggestion
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +{{- end }}
```suggestion
  maxUnavailable: 1
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +{{- end }}
```suggestion
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +    unhealthyPodEvictionPolicy: {{ .Values.resilience.pdb.unhealthyPodEvictionPolicy | quote }}
```suggestion
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
  unhealthyPodEvictionPolicy: AlwaysAllow
```

2024-10-24 12:16 UTC, vpnachev commented on charts/service-account-issuer-discovery/templates/pdb.yaml
> +          app.kubernetes.io/name: {{ include "name" . | quote }}
```suggestion
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
```

2024-10-24 12:17 UTC, vpnachev requested changes

2024-10-24 12:17 UTC, vpnachev commented on charts/service-account-issuer-discovery/values.yaml
> +
```suggestion
```

2024-10-25 12:18 UTC, vpnachev approved these changes
/lgtm

2024-10-25 13:15 UTC, merged